name: Andres - weather_project

on:
  push:
    branches: [ "andres_branch" ]
  workflow_dispatch:
     inputs: 
       log_error:
       description: 'Generate log if tests fails'
       required: true
       default: 'true'

env: 
  DOCKERFILE: ./Dockerfile
  PYTHON_VERSION: '3.11'
  IMAGE_NAME: andr18/weather_project


jobs:

  tests:
  name: Running tests
  runs-on: ubuntu-latest
  if: ${{ github.events.input.log_error == 'true' }}
  steps: 
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setting up Python 3.11
      uses: actions/setup-python@v5
      with: 
        python-version: {{ env.PYTHON_VERSION }}  

    - name: Installing dependencies
      run: pip install -r requirements.txt

    - name: Generate fail log 
      if: ${{ env.TEST_FAILED == 'true' && github.event.inputs.log_error == 'true' }}
      uses: action/upload-artifact@v4
      with:
         name: error-log 
         path: test.log


  build-and-push:
    name: Building and pushing Docker image        
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ needs.tests.results == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v6
        with: 
          context: . 
          file: ${{ env.DOCKERFILE }}
          push: true 
          tags: |
            {{ env.IMAGE_NAME }}:latest
             {{ env.IMAGE_NAME }}:1.0
